theme: jekyll-theme-minimal
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: [Tam Nguyen]

# Short bio or description (displayed in the header)
description: I create my future by code, I record my life through camera lens, I keep my memories through words, and I see the world through travel.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.facebook.com/photo.php?fbid=2068655836524955&set=a.111602872230271.14309.100001416768765&type=3&theater

logo: /pics/TamNguyen_Pro5Pic.jpg

show_downloads: true

instagram_username: nmt64

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
