theme: jekyll-theme-minimal
#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: [Tam Nguyen]

# Short bio or description (displayed in the header)
description: I create my future by code, I record my life through camera lens, I keep my memories through words, and I see the world through travel.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.facebook.com/photo.php?fbid=2068655836524955&set=a.111602872230271.14309.100001416768765&type=3&theater

logo: /pics/TamNguyen_Pro5Pic.jpg

show_downloads: true

instagram_username: https://www.instagram.com/nmt64/?hl=en
